services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  redis:
    image: "redis/redis-stack:latest"
    container_name: news-rag-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always